language: ruby
services:
 - postgresql
before_script:
 - psql -c 'create database rails_project_test;' -U postgres
test:
  adapter: postgresql
  database: rails_project_test
branches:
  only:
  - master
install:
- bundle install
addons:
    apt:
        packages:
            - sshpass
script:
  - rails db:migrate RAILS_ENV=test
  - rake test:all
env:
  global:
  - secure: 3tC9ogog76YeNVSmCKwaOIDxV8A3WFU9JhHvktS5mUMMscki9UFLDwXZPIfRdufs/CIJv8r9VqJZZ0Es2ysdXaCQYMzb7e22RhEO1u8g/8j5T6tua1tkvYxMi4lwgh99xQXvkcz0CZ1SojDShR8mR2WGw7kScbXwCfG+GuCZqR1gtSLuMBftxXJ/YPUaYijZW9O8rEeQ+yc5meFX1xI957LuWsd2sN/T+8g/5jFMeoPdtCvrvifgm4bqYH99t7Lco0mb3qaExORyyfHJcU3dQiZ9mIRYBZ287pfv0WAedUkbHsWxvjrC1vNLMopUIAZ0jbh4Eu6jDggvUkgIqBKt8RDOsXuTsztfakdOHztLpvF1MdM6WmW0483OrLocL4YWWiveH2qtbJ36llZLkd55UNCaqt39r3VAD1l7J4jq8z+M4ABPpMMIn+f0MQ5cNunf3blhwt1UnpYdI86r6trpWW3Hdl9lcqb0ZGl+bnROfUHc5wzIEXTKoxKb/4f0ZYeeL7jnWHbILBBuj5+JGd5aXDC5avAhype+7JtVW0+d5DtPMv8aur40HcbCg1F6jYTByfSGZ2R6qByfUvitnXnXV6Ze0B9TAlXXWyXStO1I5Wv8Eb0otly6CqTm5jT6yvSfHYBO1Q0g4RGjl5oj0tJPfosidqmmgN153yT+zR9gTdI=
  - secure: GINvYXlIm+Dk07LniZF5HJ2M9LI4oQj16Jxj+vobMxqvUF/JeRBThsjqXYbKGrtLsDCSMcADM8/2+zQf+0uFk9clLVPgZzLCeHomoCb3BU9UDIbjAMHO3zmMUIiQ9RE65JolKUjRmuwGFiinnvVyz54UJxRaErIcLTf4HXBIyYMe6zNhtrm5QCL2rwDNmNPterYm4sjJ6Bb4WSZaHbqs18dpfHyPY7WFftiLFVGXUnKctojBkO8EJIGIaw9fOmUp+rRU0nCkNgxklMKywnISdUra4LGdKDnKMGBdQipbHrFHIHhG+lyDXqnxMpMNN//lhPO2t0mNdUS7gvGkCZqFMoxhvmeqNVPM6xouTItiewedzGzNCUz2yXTJ7Y2berun2jDiYgWo83fvJ3JSeoDXqux4qbRjhv6Kjvop3+oXPedqwqaiQy37Cd29Uv5YET8rgeMDy60dUq2SyACzhGjOlxxvyMsJj2mO31RK+tYsyUSvuz5Zna7cZIVQT6pgcSqLJ28Vnqn0FUdqyv9UemKnlt2PDvmsf+tp5S73TZQt7K+5mbUeycGDbVmUczdju1WnwA/FbM8g5ZXKg3pnM0rtzYFNdrCgVy891R/MzuYCOT1tC9eGYAxhI2u5TN7R9R9JXpCdZA0+WXtQiQI9gdbihp/A76DRcq/RYKyFSuvSk6g=
  - secure: KpmCpANt21bo3oB7YKgyL9DuvfaEXCdQgPJdLkAicE99HBM7MNj/9U/3LUCfKx5tE8cpZl5lnpiTOsQ7eNlMRxnWAEqmCA4u2RXCH4qHZ1sNFVs+MwxjM/FW25zW/TMT/bei3cu9WA9gjjUdyqwLSFjp6g867IkkCgmiZF7gmPDDtTUvclc2ACff1cOqf2UoL+jfNKCkjJ05zGF97rCRhj6ilctzqmKuuy3zk2IixL8NpqoYcKnEVpY5/olLIHgl1+zV53kO2IyT/iC8uVGeJhipy1zxL5dqGmd6V1/OdeV+dGDEhITsMe3n7QBI8WVa8IwnYrm17PtBO0MU8xIz3oWIMkM9QZCGmiA7e3XjcLUu15YK22kSw4vxS2Z+uQu2HB5RoHYUYlVCE+sTIFE1wJaU9moXHa2MZ6K8gowIRLrQrjQ17RIqQsr/PAksJOMfFzFSTbbm9ccoBl/mx3so+cKKZhfz6k/8UKXg/sCwSq0yF4WgbFRma1nmTzZjTSth9AMEaseaeals/uw2V39yf00YecyILDrm46C1Mc7zqm7GfL+En/muyzJGprAyfGzOU7ti/28eLWCQylIncvVMFYZdjliknZWUWqcVR+eV6hwJJnAwlAWAtra/AiB1VIoRTVDALVEUzozHsKbh0bro7SrFizvcdgcaintyqZ4qv28=
  - secure: HiNSnNmJ7c46Y8FmZ2Ed9j/cPJAoWp/JtNiZHn4d9OXdsy4i+CaRdftLKFvXjH7ovUtKkvnPQ3MkXOqhbpXornDsrXYGVx8A07fvF/GOQCZjpKCgBuX2KIhljOIY49ODh7ehHlo5RKOXiV+vcYcPn6yLJL0R1RDd43yjh5IUEtASWv8Nt9NNuva1l36sPumxoHIstC8Z6VYhIub6UMqT16MnHc8nALYC+jheY9xI7d9ueOzZaM5UK8sNYt0jyzEd70/0NVdk+JBY/YqmyJudMK2kJ29tPKsmFjNCxz8ibK+gIf7Zo73aKEJNcM5tMS0P8X4LIyDaKTHIVpkABPiAzyC05aGo2iiT3PgJ/BhnQqABNYS1PInhHb3kzZqKU54YgfCu5bjhnIjt3HLqyaetgukqj4oTYpWxZpaQQJSCc495+0OhmmBgC05Q2wJPT3JCqbwN8zPYX5q7l9r0HMzApyd3lN1gZQUvruoVZHw7DhDbmU6NaF8f6h4Q+zCmOCQ9ktKSWUcvyYpDhpR+FwXNW5P3ljHpH6uCGMP4e6rL90kdZvtC7xxn7rVLDlm8xjX9k2jaRrM600lUrPZzdpaouOpH2dYdHyRiCa7edDxE+XLGuuVK/0DqGlbduMxgMXrZzlMF8h2AHrV67h3YlASi8qUl5W+zhXCpiDJT05XDrIc=
